### ISSUE TITLE
Documentacion: Intercalar diagramas con explicaciones (server)

### ISSUE THREAD

**Issue by nicolas7885** [FedericoAmura/Taller2016C1TP4MegamanInicia#8]
intercalar diagramas con contexto y explicaciones, supongo que el server mas que nada

**Comment by MarkoVrljicak** [comment]
Lo del server te lo dejo a vos Nico, porque para hacerlo yo tengo que leer todo y entenderlo.

**Comment by nicolas7885** [comment]
Ya esta
